/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t* ptr_rcc = (RCC_AHB1ENR_t*)(RCC_ADDR + RCC_OFFSET);

	ptr_rcc->GPIOA_EN = 1;
	ptr_rcc->GPIOD_EN = 1;

	GPIOx_MODER_t* ptr_mode_a = (GPIOx_MODER_t*)(GPIOA_ADDR + MODER_OFFSET);
	GPIOx_MODER_t* ptr_mode_d = (GPIOx_MODER_t*)(GPIOD_ADDR + MODER_OFFSET);

	ptr_mode_a->MODER0 = 00;
	ptr_mode_d->MODER12 = 01;
	ptr_mode_d->MODER13 = 01;
	ptr_mode_d->MODER14 = 01;
	ptr_mode_d->MODER15 = 01;

	GPIOx_IDR_t* ptr_button = (GPIOx_IDR_t*)(GPIOA_ADDR + IDR_OFFSET);
	GPIOx_ODR_t* ptr_led = (GPIOx_ODR_t*)(GPIOD_ADDR + ODR_OFFSET);

	//Interrupt A0 - APB2 Bus
	//Enable SYSCFG module - RCC
	uint32_t* ptr_rcc_apb2 = (uint32_t*)(RCC_ADDR + RCC_APB2ENR_OFFSET);
	*ptr_rcc_apb2 = *ptr_rcc_apb2 | (1 << 14);


	// SYSCFG - SYSCFG_EXTICR1 -- choose signal EXTI0
	SYSCFG_EXTICR1_t* ptr_syscfg = (SYSCFG_EXTICR1_t*)(SYSCFG_ADDR + SYSCFG_EXTICR1_OFFSET);
	ptr_syscfg->EXTI0 = 0000;

	EXTI_RTSR_t* ptr_rising = (EXTI_RTSR_t*)(EXTI_ADDR + RTSR_OFFSET);
	ptr_rising->TR0 = 1;

	//Interrupt mask register
	EXTI_IMR_t* ptr_imr = (EXTI_IMR_t*)(EXTI_ADDR + EXTI_IMR_OFFSET);
	ptr_imr->MR0 = 1;

	//NVIC
	//EXTI0 - IRQ is 6
	uint32_t* ptr_nvic = (uint32_t*)(0xE000E100 + 0x00);
	// Set bit 6 to 1 (EXTI0)
	*ptr_nvic = *ptr_nvic | (1 << 6);


	while (1) {
		ptr_led->ODR12 = 1;
		ptr_led->ODR13 = 1;
		ptr_led->ODR14 = 1;
		ptr_led->ODR15 = 1;

		for(uint32_t i = 0; i < DELAY; i++);

		ptr_led->ODR12 = 0;
		ptr_led->ODR13 = 0;
		ptr_led->ODR14 = 0;
		ptr_led->ODR15 = 0;

		for(uint32_t i = 0; i < DELAY; i++);

		while(1) {

			ptr_led->ODR15 = 0;
			ptr_led->ODR12 = 1;

			for(uint32_t i = 0; i < DELAY; i++);

			ptr_led->ODR12 = 0;
			ptr_led->ODR13 = 1;

			for(uint32_t i = 0; i < DELAY; i++);

			ptr_led->ODR13 = 0;
			ptr_led->ODR14 = 1;

			for(uint32_t i = 0; i < DELAY; i++);

			ptr_led->ODR14 = 0;
			ptr_led->ODR15 = 1;

			for(uint32_t i = 0; i < DELAY; i++);

		}

	}

}

//Function to handle interrupt
void EXTI0_IRQHandler () {
	//add delay to handle bouncing problem of button
	for (uint32_t i = 0; i < 50000; i++);

	//clear your interrupt (pending register)
	EXTI_PR_t* ptr_pending = (EXTI_PR_t*)(EXTI_ADDR + EXTI_PR_OFFSET);
	ptr_pending->PR0 = 1;

	GPIOx_IDR_t* ptr_button = (GPIOx_IDR_t*)(GPIOA_ADDR + IDR_OFFSET);
	GPIOx_ODR_t* ptr_led = (GPIOx_ODR_t*)(GPIOD_ADDR + ODR_OFFSET);

	if(ptr_button->IDR0 == 1) {
		if(ptr_led->ODR12 == 1) {
			ptr_led->ODR12 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR12 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
		}
		else if(ptr_led->ODR13 == 1) {
			ptr_led->ODR13 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR13 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
		}
		else if(ptr_led->ODR14 == 1) {
			ptr_led->ODR14 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR14 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
		}
		else if(ptr_led->ODR15 == 1) {
			ptr_led->ODR15 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 0;
			for (uint32_t i = 0; i < DELAY; i++);
			ptr_led->ODR15 = 1;
			for (uint32_t i = 0; i < DELAY; i++);
		}
	}
}







