/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	RCC_AHB1ENR_t* ptr_rcc = (RCC_AHB1ENR_t*)(0x40023800 + 0x30);

	ptr_rcc->GPIOA_EN = 1;
	ptr_rcc->GPIOD_EN = 1;

	GPIOx_MODER_t* ptr_mode_a = (GPIOx_MODER_t*)(0x40020000 + 0x00);
	GPIOx_MODER_t* ptr_mode_d = (GPIOx_MODER_t*)(0x40020C00 + 0x00);

	ptr_mode_a->MODER0 = 00;
	ptr_mode_d->MODER12 = 01;
	ptr_mode_d->MODER13 = 01;
	ptr_mode_d->MODER14 = 01;
	ptr_mode_d->MODER15 = 01;

	GPIOx_ODR_t* ptr_odr_d = (GPIOx_ODR_t*)(0x40020C00 + 0x14);
	GPIOx_IDR_t* ptr_idr_a = (GPIOx_IDR_t*)(0x40020000 + 0x10);


	while(1) {
		// here 1

		if(ptr_idr_a->IDR0 == 1) {
			ptr_odr_d->ODR12 = 1;
			ptr_odr_d->ODR13 = 1;
			ptr_odr_d->ODR14 = 1;
			ptr_odr_d->ODR15 = 1;

			for (int i = 0; i < DELAY; i++);

			ptr_odr_d->ODR12 = 0;
			ptr_odr_d->ODR13 = 0;
			ptr_odr_d->ODR14 = 0;
			ptr_odr_d->ODR15 = 0;

			for (int i = 0; i < 500000; i++);
		}
		else {
			ptr_odr_d->ODR12 = 1;

			for (int i = 0; i < 500000; i++);

			ptr_odr_d->ODR15 = 1;
			ptr_odr_d->ODR12 = 0;

			for (int i = 0; i < 500000; i++);

			ptr_odr_d->ODR14 = 1;
			ptr_odr_d->ODR15 = 0;

			for (int i = 0; i < 500000; i++);

			ptr_odr_d->ODR13 = 1;
			ptr_odr_d->ODR14 = 0;

			for (int i = 0; i < 500000; i++);

			ptr_odr_d->ODR13 = 0;
		}

		// here 2
	}


}
